#!/bin/bash
read -p "Enter size: " size
read -p "Enter suffix: " SUFFIX

for file in $(pwd)/*
    do
    name=$(du $file | cut -f2)
    suffixFile=${name##*.}
    if [[ -x $file ]] && [[ $(du $file | cut -f1) -le $size ]] && [[ "$suffixFile" == "$SUFFIX" ]]; then
        du -h $file >> result.txt
    fi
done